import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

cleanupOutdatedCaches()

self.addEventListener('push', (event) => {
    if (!event.data) return;

    let data = {};
    try {
        data = event.data.json();
    } catch (e) {
        data = { title: 'New Message', body: event.data.text() };
    }

    const isIncomingCall = data?.data?.type === 'incoming_call';

    const silent = Boolean(data.silent);

    const options = {
        body: data.body || 'You have a new message.',
        icon: data.icon || '/pwa-192x192.png',
        badge: data.badge || '/pwa-192x192.png',
        silent,
        tag: data.tag || 'message-notification',
        renotify: Boolean(data.renotify),
        requireInteraction: Boolean(data.requireInteraction),
        data: data.data || {},
        actions: isIncomingCall
            ? [
                { action: 'open_call', title: 'Open Call' },
                { action: 'dismiss', title: 'Dismiss' }
            ]
            : []
    };

    if (!silent) {
        options.vibrate = data.vibrate || [100, 50, 100];
    }

    const title = data.title || 'New Message';

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    if (event.action === 'dismiss') return;

    const notificationData = event.notification.data || {};
    const urlToOpen = notificationData.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if ('focus' in client) {
                    return client.focus().then(() => {
                        if ('navigate' in client) {
                            return client.navigate(urlToOpen);
                        }
                        return client;
                    });
                }
            }
            // Otherwise open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
